apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-assistant
  namespace: conversational-assistant
  labels:
    app: conv-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-assistant
  template:
    metadata:
      labels:
        app: conv-assistant
    spec:
      containers:
        - name: conv-assistant
          image: conversational-assistant:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api
                  key: OPENAI_API_KEY
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: conv-assistant
  namespace: conversational-assistant
  labels:
    app: conv-assistant
spec:
  type: NodePort
  selector:
    app: conv-assistant
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080

